// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaWebPizzaria.Models;

namespace SistemaWebPizzaria.Migrations
{
    [DbContext(typeof(BancoPizzariaContext))]
    [Migration("20200921022121_delcascade")]
    partial class delcascade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaWebPizzaria.Models.Cardapiopizza", b =>
                {
                    b.Property<int>("IdCardapio")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sabor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tamanho")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdCardapio");

                    b.ToTable("cardapiopizza");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdCliente");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Despesa", b =>
                {
                    b.Property<int>("IdDespesa")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataDespesa")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDespesa");

                    b.ToTable("despesa");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Cep")
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("ClienteIdCliente")
                        .HasColumnName("Cliente_IdCliente");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Numero")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rua")
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdEndereco");

                    b.HasIndex("ClienteIdCliente")
                        .HasName("fk_Endereco_Cliente1_idx");

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Celular")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasName("CPF_Func_UNIQUE");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Itemcardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdCardapio");

                    b.Property<int>("IdPedido");

                    b.Property<decimal?>("PrecoUnidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Quantidade");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCardapio")
                        .HasName("fk_tbCardapio_has_tbPedido_tbCardapio1_idx");

                    b.HasIndex("IdPedido")
                        .HasName("fk_tbCardapio_has_tbPedido_tbPedido1_idx");

                    b.ToTable("itemcardapio");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Itemproduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdPedido");

                    b.Property<int>("IdProduto");

                    b.Property<decimal?>("PrecoUnidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("QtdeProduto");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .HasName("fk_tbPedido_has_tbProduto_tbPedido1_idx");

                    b.HasIndex("IdProduto")
                        .HasName("fk_tbPedido_has_tbProduto_tbProduto1_idx");

                    b.ToTable("itemproduto");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("IdFuncionario");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdLogin");

                    b.HasIndex("IdFuncionario")
                        .HasName("fk_Login_Funcionario1_idx");

                    b.ToTable("login");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdFuncioario");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("TotalPedido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente")
                        .HasName("fk_tbPedido_tbCliente1_idx");

                    b.HasIndex("IdFuncioario")
                        .HasName("fk_tbPedido_tbFuncionario1_idx");

                    b.HasIndex("IdPedido")
                        .IsUnique()
                        .HasName("IdPedido_UNIQUE");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Produtoestoque", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeFornecedor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValorTributos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Vende")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("IdProduto");

                    b.ToTable("produtoestoque");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Endereco", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Models.Cliente", "ClienteIdClienteNavigation")
                        .WithMany("Endereco")
                        .HasForeignKey("ClienteIdCliente")
                        .HasConstraintName("ON DELETE CASCADE");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Itemcardapio", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Models.Cardapiopizza", "IdCardapioNavigation")
                        .WithMany("Itemcardapio")
                        .HasForeignKey("IdCardapio")
                        .HasConstraintName("fk_tbCardapio_has_tbPedido_tbCardapio1");

                    b.HasOne("SistemaWebPizzaria.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Itemcardapio")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("fk_tbCardapio_has_tbPedido_tbPedido1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Itemproduto", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Models.Pedido", "IdPedidoNavigation")
                        .WithMany("Itemproduto")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("fk_tbPedido_has_tbProduto_tbPedido1");

                    b.HasOne("SistemaWebPizzaria.Models.Produtoestoque", "IdProdutoNavigation")
                        .WithMany("Itemproduto")
                        .HasForeignKey("IdProduto")
                        .HasConstraintName("fk_tbPedido_has_tbProduto_tbProduto1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Login", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Models.Funcionario", "IdFuncionarioNavigation")
                        .WithMany("Login")
                        .HasForeignKey("IdFuncionario")
                        .HasConstraintName("fk_Login_Funcionario1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Models.Pedido", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("fk_tbPedido_tbCliente1");

                    b.HasOne("SistemaWebPizzaria.Models.Funcionario", "IdFuncioarioNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdFuncioario")
                        .HasConstraintName("fk_tbPedido_tbFuncionario1");
                });
#pragma warning restore 612, 618
        }
    }
}
