// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaWebPizzaria;

namespace SistemaWebPizzaria.Migrations
{
    [DbContext(typeof(BancoPizzariaContext))]
    partial class BancoPizzariaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SistemaWebPizzaria.Cardapio", b =>
                {
                    b.Property<int>("IdCardapio")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sabor")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tamanho")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdCardapio");

                    b.ToTable("cardapio");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .HasColumnType("varchar(45)");

                    b.Property<int>("TbEnderecoIdEndereco")
                        .HasColumnName("tbEndereco_IdEndereco");

                    b.Property<string>("Telefone")
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasName("IdCliente_UNIQUE");

                    b.HasIndex("TbEnderecoIdEndereco")
                        .HasName("fk_tbCliente_tbEndereco1_idx");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Despesa", b =>
                {
                    b.Property<int>("IdDespesa")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DataDespesa")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeDespesa")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDespesa");

                    b.ToTable("despesa");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Endereco", b =>
                {
                    b.Property<int>("IdEndereco")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnName("CEP")
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Cidade")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdEndereco");

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ativo")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("Celular")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("IdLogin");

                    b.Property<int>("IdPerfil");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasName("CPF_Func_UNIQUE");

                    b.HasIndex("IdLogin")
                        .HasName("fk_tbFuncionario_tbLogin_idx");

                    b.HasIndex("IdPerfil")
                        .HasName("fk_tbFuncionario_tbPerfil1_idx");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Itemcardapio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdCardapio");

                    b.Property<int>("IdPedido");

                    b.Property<decimal?>("PrecoUnidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("Quantidade");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdCardapio")
                        .HasName("fk_tbCardapio_has_tbPedido_tbCardapio1_idx");

                    b.HasIndex("IdPedido")
                        .HasName("fk_tbCardapio_has_tbPedido_tbPedido1_idx");

                    b.ToTable("itemcardapio");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Itemproduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdPedido");

                    b.Property<int>("IdProduto");

                    b.Property<decimal?>("PrecoUnidade")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("QtdeProduto");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdPedido")
                        .HasName("fk_tbPedido_has_tbProduto_tbPedido1_idx");

                    b.HasIndex("IdProduto")
                        .HasName("fk_tbPedido_has_tbProduto_tbProduto1_idx");

                    b.ToTable("itemproduto");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Login", b =>
                {
                    b.Property<int>("IdLogin")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("IdLogin");

                    b.ToTable("login");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdFuncioario");

                    b.Property<string>("TipoEntrega")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("TotalPedido")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente")
                        .HasName("fk_tbPedido_tbCliente1_idx");

                    b.HasIndex("IdFuncioario")
                        .HasName("fk_tbPedido_tbFuncionario1_idx");

                    b.HasIndex("IdPedido")
                        .IsUnique()
                        .HasName("IdPedido_UNIQUE");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Perfil", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("idPerfil");

                    b.Property<string>("TipoPerfil")
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdPerfil");

                    b.ToTable("perfil");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Marca")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NomeFornecedor")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("PrecoCompra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantidade");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime?>("Validade")
                        .HasColumnType("date");

                    b.Property<decimal?>("ValorTributos")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdProduto");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Cliente", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Endereco", "TbEnderecoIdEnderecoNavigation")
                        .WithMany("Cliente")
                        .HasForeignKey("TbEnderecoIdEndereco")
                        .HasConstraintName("fk_tbCliente_tbEndereco1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Funcionario", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Login", "IdLoginNavigation")
                        .WithMany("Funcionario")
                        .HasForeignKey("IdLogin")
                        .HasConstraintName("fk_tbFuncionario_tbLogin");

                    b.HasOne("SistemaWebPizzaria.Perfil", "IdPerfilNavigation")
                        .WithMany("Funcionario")
                        .HasForeignKey("IdPerfil")
                        .HasConstraintName("fk_tbFuncionario_tbPerfil1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Itemcardapio", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Cardapio", "IdCardapioNavigation")
                        .WithMany("Itemcardapio")
                        .HasForeignKey("IdCardapio")
                        .HasConstraintName("fk_tbCardapio_has_tbPedido_tbCardapio1");

                    b.HasOne("SistemaWebPizzaria.Pedido", "IdPedidoNavigation")
                        .WithMany("Itemcardapio")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("fk_tbCardapio_has_tbPedido_tbPedido1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Itemproduto", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Pedido", "IdPedidoNavigation")
                        .WithMany("Itemproduto")
                        .HasForeignKey("IdPedido")
                        .HasConstraintName("fk_tbPedido_has_tbProduto_tbPedido1");

                    b.HasOne("SistemaWebPizzaria.Produto", "IdProdutoNavigation")
                        .WithMany("Itemproduto")
                        .HasForeignKey("IdProduto")
                        .HasConstraintName("fk_tbPedido_has_tbProduto_tbProduto1");
                });

            modelBuilder.Entity("SistemaWebPizzaria.Pedido", b =>
                {
                    b.HasOne("SistemaWebPizzaria.Cliente", "IdClienteNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("fk_tbPedido_tbCliente1");

                    b.HasOne("SistemaWebPizzaria.Funcionario", "IdFuncioarioNavigation")
                        .WithMany("Pedido")
                        .HasForeignKey("IdFuncioario")
                        .HasConstraintName("fk_tbPedido_tbFuncionario1");
                });
#pragma warning restore 612, 618
        }
    }
}
